name: 'Contributor Submodules Action'
description: 'A Action that automates adding submodules'
author: 'noahreinalter'
branding:
  icon: folder-plus
  color: orange
inputs:
  url:
    description: 'Url to the git repo'
  regex:
    description: 'Regex for the folders to link'
    default: '^\d*$'
  reload_submodules:
    description: 'Adds links for submodules if they are missing'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
