name: 'Contributor Submodules Action'
description: 'A Action that automates adding submodules'
author: 'noahreinalter'
branding:
  icon: folder-plus
  color: orange
inputs:
  url:
    description: 'Url to the git repo'
  users:
    description: 'Allowed users(space separated) to add new submodules'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
