name: 'Contributor Submodules Action'
description: 'A Action that automates adding submodules'
author: 'noahreinalter'
branding:
  icon: folder-plus
  color: orange
inputs:
  url:
    description: 'Url to the git repo'
  regex:
    description: 'Regex for the folders to link'
    default: '^\d*$'
  relink_submodules:
    description: 'Adds symlinks for folders matching the regex if they are missing'
    default: 'false'
  update_submodules:
    description: 'Fetch and update all submodules'
    default: 'false'
  submodule_save_location:
    description: 'Path where all the submodules are'
    default: 'submodules'

runs:
  using: 'node16'
  main: 'dist/index.js'
